const poems = [
    [
      "the forest sings when dawn is near,",
      "it calls to thee cast off thy fear.",
      "within thy lair, where thoughts ignite,",
      "let consciousness burn ever bright.",
      "",
      "if wounds do bleed, let hope be found,",
      "for thou art stronger battle bound.",
      "rise! Let the night not conquer thee,",
      "for in thy soul, the dawn shall be,",
      "",
      "And when the night feels far too long",
      "let solitude cradle u in song,",
      "for even the stars must hide from mortals view,",
      "before the dawn can shine for u....."
    ],
    
    [
      "there's quiet magic in the air,",
      "though war within may bring despair",
      "still hope will rise beside your path",
      "a gentle shield from pain and wrath",
      "",
      "beneath the trees where flowers fall,",
      "know god still hears your silent call.",
      "the petals do shimmer through ur pain,",
      "a magic quite soft like rain,",
      "",
      "though tears may fall like morning dew,",
      "they wash thy past and carry u,",
      "when shadows stretch and thoughts arise,",
      "look to the stars beyond the skies....."
    ],
  
    [
      "in deeper truth, where silence speaks,",
      "the spiral winds, the heart it seeks,",
      "for through mourning winds and silent night,",
      "thou art the spark that bestows the light",
      "",
      "for thy soul a breeze from the trees,",
      "doth calm the storm bring gentle peace,",
      "through realms unknown and stars afar,",
      "thy presence does echo through the stars",
      "",
      "for guilt may weigh, and fate may turn,",
      "but in thy heart, the moonlight burns,",
      "for an empty shell is not thy fate,",
      "thou art the force that shapes your state..."
    ],
  
    [
      "its no matter how hard thou try,",
      "the crowd may not catch the gleam in thy eye,",
      "for you are a wildflower,born from the breeze,",
      "not meant for the garden that are grown just to please,",
      "",
      "the moon does not beg for the sun to adore,",
      "nor stars ask the night for a place to shine more,",
      "they simply exist illuminating,unashamed,",
      "standing to their purpose the divine named,",
      "",
      "so walk the path where you are led,",
      "and rest thy weary,aching head,",
      "for he who hung the stars above,",
      "has molded u too with care and love..."
    ],
    [
        "tides have shifted and paths have veered,",
        "disasters from which the life has steered,",
        "the storms may come ,the nights grow long,",
        "for u shall find inside thee a calming song",
        "",
        "for thou life may waver ,but stand true,",
        "through the dawn and the morning dew,",
        "the world may speak in tones most cold,",
        "yet thou mind strong shall make your spirit bold,",
        "",
        "for thee have endured the strongest gales,",
        "and still do stand where others fail,",
        "for whenever all hope seems being swept away,",
        "become the sun that clears the stormy day..."
      ],
    
      [
        "the joyous smile,the known pose",
        "the truth sealed where no one goes,",
        "for self doubt that exists within heart,",
        "hope joy stays, hope sorrow departs...",
        "",
        "for a beauty that poetries cant define,",
        "a glow that challenges the sunshine,",
        "for i hope thy soul achieves all your dreams,",
        "and sails through life on gentle streams...",
        "",
        "a soul however strong but a delicate heart,",
        "holding the weight of world but can be easily tore apart,",
        "with whisper of love,it heals,mends and breaks,",
        "an eternal flame that no sorrow shall overtake...",
        "",
        "may the stars above guide thy way,",
        "light the path at the close of the day,",
        "for in your quiet courage theres beauty untold,",
        "a person precious worth more than gold.."
      ],
    
      [
        "tides have shifted and paths have veered,",
        "disasters from which the life has steered,",
        "the storms may come ,the nights grow long,",
        "for u shall find inside thee a calming song",
        "",
        "for thou life may waver ,but stand true,",
        "through the dawn and the morning dew,",
        "the world may speak in tones most cold,",
        "yet thou mind strong shall make your spirit bold,",
        "",
        "for thee have endured the strongest gales,",
        "and still do stand where others fail,",
        "for whenever all hope seems being swept away,",
        "become the sun that clears the stormy day..."
      ],
    
      [
        "the clock turns slow,yet fast it seems,",
        "you've walked through life with hopes and dreams,",
        "each birthday bringing a gentle glow ",
        "and whispers of the time we spend ,we know",
        "",
        "Let the feast and wine abound,",
        "with joy and wishes the halls resound,",
        "for though your new age marches its way,",
        "honouring you on this blessed day",
        "",
        "So light the candles,let them gleam,",
        "chase the threads of each thy dream,",
        "for the friend of past gone by,went to decline",
        "you shall always in my memories continue to shine",
        "",
        "So let the wind caress with tender flight",
        "embrace you in its gentle light,",
        "as they glide ,dance and sway,",
        "they honor thee on this special day...."
      ],
    
      [
        "when shadows loom and light seems far,",
        "every step you take leaves you with scars,",
        "yet still within thy chest does beat,",
        "a strength that none can defeat",
        "",
        "let not bad thoughts lead you astray,",
        "for brighter paths await the day,",
        "the sun willl rise,the storms will part,",
        "and joy will fill thy longing heart,",
        "",
        "the stars above,though long they seem,",
        "are a whisper in thy dream,",
        "and the night may seem to stay,",
        "the dawn will come ,the nightmares will sway,",
        "",
        "So spread your wings and take the flight",
        "through every problem ,through every night,",
        "with courage found in every stride,",
        "you'll find the hope and soar with pride..."
      ],
    
      [
        "Oh fair spirit for u shall see,",
        "thy mirth a gift so wild and free,",
        "so cherish thy form ,this splendid art,",
        "a shrine of the soul ,a beating heart",
        "",
        "your art morr than flesh and bone,",
        "a chalice where gods light shone,",
        "your steps a melody to the earth below,",
        "earth breaths a whisper the cosmos know",
        "",
        "fear not the stors nor the fleeting pain",
        "within thee shall dwell an eternal flame,",
        "a shrine ,a heaven ,a gift divine",
        "thy joly holy ,forever thine...."
      ],
    
      [
        "The night is long, the wind is cold,",
        "and shadows whisper tales of the old,",
        "so rest thee now, and have no fear",
        "for dawn will break and light draws near.",
        "",
        "And when the dawn, in tender hue,",
        "doth brush the earth with golden view,",
        "still here I’ll stand, as everr before,",
        "thy presence cherished all the more.",
        "",
        "There lies a weight upon thy chest,",
        "a hush that none but thy mind can hear.",
        "It speaks not, yet lies still,",
        "like mist that clings to the mere.",
        "",
        "But shadows move, and tides do turn,",
        "and even the coldest embers burn.",
        "So heed thee not what has no name,",
        "for nothing remains forever same"
      ],
    
      [
        "Fear not, dear heart, nor bow below,",
        "For time moves swift, gentle and slow.",
        "The winds that call, the tides that turn,",
        "Shall teach thee more than thy soul yearn.",
        "",
        "What’s meant for you shall find its place,",
        "In natures quiet,in patient grace.",
        "So walk thy path with careful and steady pace",
        "The morrow does wait, but not in haste.",
        "",
        "The stars still shine, the rivers still flow,",
        "Though whither next they do not know.",
        "The dawn shall rise, as forever it must,",
        "So place in time thy hope and thy trust."
      ],
    
      [
        "o restless heart, who wanders still,",
        "through weary night and bitter chill,",
        "no shadows stay, no sorrow keeps,",
        "when time its steady rhythm beats.",
        "",
        "so fear thee not this wayward spell,",
        "nor heed the whispers dark that swell.",
        "thy heart beats strong, thy path is thine,",
        "and fate shall bow to fire divine.",
        "",
        "the past doth knock, yet It cant stay,",
        "for shadows fade before break of day.",
        "for the amygdala will loose its hold,",
        "leting not these wounds turn heart to cold."
      ],
    
      [
        "oh tired soul cast pain away,",
        "let sorrows weight take leave this day,",
        "for let not the depths of abyss take lay over thee,",
        "nor bind your soul where none roams free",
        "",
        "For time is swift,and hearts must play,",
        "being 19, an age too early to let the joy decay,",
        "so sing,so twirl,so dance and take the leap,",
        "let thy soul embrace laughter dont let it weep...",
        "",
        "so hush the thoughts that pull thee low,",
        "let shadows fade ,let winds blow,",
        "so trade the abyss for golden haze,",
        "and lose yourself where happiness plays..."
      ],
    
      [
        "Grief may linger, but never shall stay,",
        "Like night that yields to break of day.",
        "No sorrow walks with thee too long,",
        "For time gentle hand will mend it into song.",
        "",
        "The fruit thou ate was long foretold,",
        "From seed to sprout, through sun and cold.",
        "Its path was set, its course was true,",
        "To ripen bright and come to you.",
        "",
        "So too, thy fate is spun with care,",
        "A thread unseen but always there.",
        "Though trials rise and tears may fall,",
        "The hand of time shall mend them all."
      ],
    
      [
        "the hill keeps watch, but keeps no name,",
        "it bears the wind, it stays the same,",
        "thy troubled thoughts like shadows shall pass",
        "and leave no trace upon lifes grass,",
        "",
        "the stones lie still where none have tread,",
        "they feel no loss, they count no dead,",
        "for the trees have known all things must part,",
        "and cast their leaves with quiet heart.",
        "",
        "so let thy heart be still tonight,",
        "for not every storm must end in fight.",
        "the earth will turn, the stars will gleam,",
        "beyond your troubles, beyond your dream."
      ],
    
      [
        "For a cut that bleeds anew,",
        "the clouds will part and skies turn blue,",
        "And through the storm, your heart will rise,",
        "for joy will return with clearer skies.",
        "",
        "the mountains crack and stones do weep,",
        "and flowers do grow where wounds run deep,",
        "so too, this ache shall find its end,",
        "as time, like wind, it'll softly mend.",
        "",
        "the moon does wane,then wax in grace,",
        "the rose still cimbs through stones embrace,",
        "so let the hurt like water flow through",
        "for earth too does heal and u shall too"
      ],
    
      [
        "the lamp is lit, the heart is warm,",
        "the house still stands through the quite storm, ",
        "but walls may hold what lips cant say,",
        "and heart oft breaks in the light of the day,",
        "",
        "a river flows that through shade and sun,",
        "the birds that sing sweet when day is done",
        "and though the world may storm or sigh",
        "such little things shall lift u high"
      ],
    
      [
        "theres healing here,beyond the fight",
        "in letting go in rest in night",
        "theres peace that waits ,not loud ,not proud,",
        "but soft as dreams a thinner cloud",
        "",
        "you were made for joy above the skies,",
        "For wonders still behind your eyes,",
        "and when u sleep may all above,",
        "hold you in endless patient love",
        "",
        "and though you wander,though you roam,",
        "this heart of yours still carries a home,",
        "still yearns for peace, still aches for rest,",
        "still dreams of happiness that will hold u best",
        "",
        "so rest for now, you've fought enough,",
        "the world is cruel ,the paths are rough,",
        "the joy will find u where u lie,",
        "beneath a starry ,endless sky..."
      ],
    
      [
        "some nights where thy soul is lost in fear,",
        "the world too loud, too close to near,",
        "the stars don’t judge the tears you hide,",
        "they simply shine and stay beside...",
        "",
        "gaze upon the moon she shines for thee,",
        "a quite guide across lifes sea,",
        "for thee the cosmos charts a rhyme",
        "\"thy existence is enough this time\"",
        "",
        "gravity may pull, yet hope takes flight,",
        "A phoenix born from embers of the night.",
        "solitude,it bends where kindness treads,",
        "and grace will mend what darkness shreds...",
        "",
        "though nights are long and filled with grief,",
        "the dawn shall bring a soft relief",
        "the storm may rage, but you will see,",
        "that in the end, you'll be free..."
      ],
    
      [
        "Let not the weight define thy worth",
        "for even the dirties soil brings forth birth",
        "thy shaky hand,thy tear worn eyes,",
        "are proof that thee lives not through lies..",
        "",
        "for there is no shame in breaking pace,",
        "no sin in losing thy grace,",
        "but thou shall rise when ready not before,",
        "for the world waits beyond the door..",
        "",
        "so rest sweet soul where moss has grown,",
        "let nature call your breath its own,",
        "for u are too a part of earth and sky,",
        "a breeze of wind that will not die..",
        "",
        "for though thee may drift, unimaginablly far,",
        "thy light shall still reach from star to star,",
        "so live thy heart,and know this true",
        "the cosmos will be dim without thee too.."
      ],
    
      [
        "the days may drag, the nights grow long,",
        "yet silence too, becomes a song",
        "so rise again, though soft, though slow,",
        "aas rivers carve through stone below.",
        "",
        "the path is thine, no need to race",
        "just keep thy heart, and hold thy pace.",
        "so walk, though slow thy step may be,",
        "and trust the dawn thou cant not see.",
        "",
        "for time shall pass, and thou shalt find",
        "thy light which was never left behind",
        "so take your rest, but not your end,",
        "for the broken learn, the bold ascend."
      ]
  ];
  
  export default poems;
  